<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/GigYWy2UmOY</id><published>2008-07-21T15:08:59.000Z</published><updated>2013-03-04T09:32:24.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Entertainment' label='Entertainment'/><title type='text'>Keith Barry: Brain magic</title><content type='text'>http://www.ted.com First, Keith Barry shows us how our brains can fool our bodies -- in a trick that works via podcast too. Then he involves the audience in some jaw-dropping (and even a bit dangerous) feats of brain magic.

TEDTalks is a daily video podcast of the best talks and performances from the TED Conference, where the world's leading thinkers and doers give the talk of their lives in 18 minutes. TED stands for Technology, Entertainment, Design, and TEDTalks cover these topics as well as science, business, development and the arts. Closed captions and translated subtitles in a variety of languages are now available on TED.com, at http://www.ted.com/translate.

Follow us on Twitter
http://www.twitter.com/tednews
 
Checkout our Facebook page for TED exclusives
https://www.facebook.com/TED</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=GigYWy2UmOY&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/GigYWy2UmOY/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/GigYWy2UmOY/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=GigYWy2UmOY'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/GigYWy2UmOY'/><author><name>TEDtalksDirector</name><uri>http://gdata.youtube.com/feeds/api/users/TEDtalksDirector</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/GigYWy2UmOY/comments' countHint='2525'/></gd:comments><media:group><media:category label='Entertainment' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Entertainment</media:category><media:content url='http://www.youtube.com/v/GigYWy2UmOY?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='1190' yt:format='5'/><media:content url='rtsp://v7.cache6.c.youtube.com/CiILENy73wIaGQnmmJQtWxgoGhMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='1190' yt:format='1'/><media:content url='rtsp://v7.cache6.c.youtube.com/CiILENy73wIaGQnmmJQtWxgoGhMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='1190' yt:format='6'/><media:description type='plain'>http://www.ted.com First, Keith Barry shows us how our brains can fool our bodies -- in a trick that works via podcast too. Then he involves the audience in some jaw-dropping (and even a bit dangerous) feats of brain magic.

TEDTalks is a daily video podcast of the best talks and performances from the TED Conference, where the world's leading thinkers and doers give the talk of their lives in 18 minutes. TED stands for Technology, Entertainment, Design, and TEDTalks cover these topics as well as science, business, development and the arts. Closed captions and translated subtitles in a variety of languages are now available on TED.com, at http://www.ted.com/translate.

Follow us on Twitter
http://www.twitter.com/tednews
 
Checkout our Facebook page for TED exclusives
https://www.facebook.com/TED</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=GigYWy2UmOY&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/GigYWy2UmOY/0.jpg' height='360' width='480' time='00:09:55'/><media:thumbnail url='http://i.ytimg.com/vi/GigYWy2UmOY/1.jpg' height='90' width='120' time='00:04:57.500'/><media:thumbnail url='http://i.ytimg.com/vi/GigYWy2UmOY/2.jpg' height='90' width='120' time='00:09:55'/><media:thumbnail url='http://i.ytimg.com/vi/GigYWy2UmOY/3.jpg' height='90' width='120' time='00:14:52.500'/><media:title type='plain'>Keith Barry: Brain magic</media:title><yt:duration seconds='1190'/></media:group><gd:rating average='4.6133666' max='5' min='1' numRaters='7242' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='1232004'/></entry>