<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/j6Nwdpa5PcU</id><published>2012-06-27T16:20:36.000Z</published><updated>2013-03-05T14:53:44.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Film' label='Film &amp; Animation'/><title type='text'>EPIC Trailer 2013 Movie - Official [HD]</title><content type='text'>Epic Trailer 2013 Movie - Official 2012 trailer in HD - Animated Adventure-Comedy starring Colin Farrell, Amanda Seyfried, Josh Hutcherson, and Beyonce Knowles - directed by Chris Wedge - a 3D CG movie that reveals a hidden world unlike any other

Epic movie hits theaters on May 17, 2013.

EPIC tells the story of an ongoing battle deep in the forest between the forces of good and the forces of evil.  When a teen age girl finds herself magically transported into this secret universe, she must band together with a rag-tag team of fun and whimsical characters in order to save their world...and ours. Epic movie trailer 2013 is presented in full HD 1080p high resolution. 

EPIC 2013 Movie
Director: Chris Wedge
Writers: Tom J. Astle, Matt Ember
Stars: Colin Farrell, Amanda Seyfried, Josh Hutcherson and Beyonce Knowles.

Epic official movie trailer courtesy 20th Century Fox.

Cieon Movies is your daily dose of "everything movies", a mainstream channel with wider coverage from G-rated to R-rated movies and includes both theatrical and DVD releases, with an extended selection of officially licensed movie trailers and movie clips.

Tags: "epic trailer" "epic 2013" epic trailer 2013 official hd movie 2012 "epic trailer 2013" "epic trailer 2012" "epic movie" "epic movie trailer" "epic 2013 movie" "epic 2013 trailer" "colin farrell" "amanda seyfried" "josh hutcherson" "beyonce knowles" "chris wedge" colin farrell amanda seyfried hutcherson beyonce knowles chris wedge movies trailers film films today this week month year new "official trailer" "movie trailer" "film trailer" "trailer 2013" "trailer 2012"</content><link rel='http://gdata.youtube.com/schemas/2007#video.in-response-to' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/9w8lE83oYeM'/><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=j6Nwdpa5PcU&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/j6Nwdpa5PcU/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/j6Nwdpa5PcU/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=j6Nwdpa5PcU'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/j6Nwdpa5PcU'/><author><name>CieonMovies</name><uri>http://gdata.youtube.com/feeds/api/users/CieonMovies</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/j6Nwdpa5PcU/comments' countHint='1853'/></gd:comments><yt:hd/><media:group><media:category label='Film &amp; Animation' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Film</media:category><media:content url='http://www.youtube.com/v/j6Nwdpa5PcU?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='138' yt:format='5'/><media:content url='rtsp://r2---sn-a5m7zu76.c.youtube.com/CiILENy73wIaGQnFPbmWdnCjjxMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='138' yt:format='1'/><media:content url='rtsp://r2---sn-a5m7zu76.c.youtube.com/CiILENy73wIaGQnFPbmWdnCjjxMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='138' yt:format='6'/><media:description type='plain'>Epic Trailer 2013 Movie - Official 2012 trailer in HD - Animated Adventure-Comedy starring Colin Farrell, Amanda Seyfried, Josh Hutcherson, and Beyonce Knowles - directed by Chris Wedge - a 3D CG movie that reveals a hidden world unlike any other

Epic movie hits theaters on May 17, 2013.

EPIC tells the story of an ongoing battle deep in the forest between the forces of good and the forces of evil.  When a teen age girl finds herself magically transported into this secret universe, she must band together with a rag-tag team of fun and whimsical characters in order to save their world...and ours. Epic movie trailer 2013 is presented in full HD 1080p high resolution. 

EPIC 2013 Movie
Director: Chris Wedge
Writers: Tom J. Astle, Matt Ember
Stars: Colin Farrell, Amanda Seyfried, Josh Hutcherson and Beyonce Knowles.

Epic official movie trailer courtesy 20th Century Fox.

Cieon Movies is your daily dose of "everything movies", a mainstream channel with wider coverage from G-rated to R-rated movies and includes both theatrical and DVD releases, with an extended selection of officially licensed movie trailers and movie clips.

Tags: "epic trailer" "epic 2013" epic trailer 2013 official hd movie 2012 "epic trailer 2013" "epic trailer 2012" "epic movie" "epic movie trailer" "epic 2013 movie" "epic 2013 trailer" "colin farrell" "amanda seyfried" "josh hutcherson" "beyonce knowles" "chris wedge" colin farrell amanda seyfried hutcherson beyonce knowles chris wedge movies trailers film films today this week month year new "official trailer" "movie trailer" "film trailer" "trailer 2013" "trailer 2012"</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=j6Nwdpa5PcU&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/j6Nwdpa5PcU/0.jpg' height='360' width='480' time='00:01:09'/><media:thumbnail url='http://i.ytimg.com/vi/j6Nwdpa5PcU/1.jpg' height='90' width='120' time='00:00:34.500'/><media:thumbnail url='http://i.ytimg.com/vi/j6Nwdpa5PcU/2.jpg' height='90' width='120' time='00:01:09'/><media:thumbnail url='http://i.ytimg.com/vi/j6Nwdpa5PcU/3.jpg' height='90' width='120' time='00:01:43.500'/><media:title type='plain'>EPIC Trailer 2013 Movie - Official [HD]</media:title><yt:duration seconds='138'/></media:group><gd:rating average='4.9041386' max='5' min='1' numRaters='9013' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='1626148'/></entry>