<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/nKIu9yen5nc</id><published>2013-02-26T14:00:29.000Z</published><updated>2013-03-04T06:32:51.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Education' label='Education'/><title type='text'>What most schools don't teach</title><content type='text'>Learn about a new "superpower" that isn't being taught in in 90% of US schools. 

Starring Bill Gates, Mark Zuckerberg, will.i.am, Chris Bosh, Jack Dorsey, Tony Hsieh, Drew Houston, Gabe Newell, Ruchi Sanghvi, Elena Silenok, Vanessa Hurst, and Hadi Partovi. Directed by Lesley Chilcott.

Code.org owes special thanks to all the cast and the film crew, and also Microsoft, Google/YouTube, Facebook, Amazon, and Twitter for helping us spread the word

(spanish translations by UruIT Team" http://uruit.com/ and Luisa Velarde. Portuguese by Rafael Sagula. If you want to help translate to other languages, visit http://bit.ly/codetranslate)</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=nKIu9yen5nc&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/nKIu9yen5nc/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/nKIu9yen5nc/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=nKIu9yen5nc'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/nKIu9yen5nc'/><author><name>CodeOrg</name><uri>http://gdata.youtube.com/feeds/api/users/CodeOrg</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/nKIu9yen5nc/comments' countHint='14131'/></gd:comments><yt:hd/><media:group><media:category label='Education' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Education</media:category><media:content url='http://www.youtube.com/v/nKIu9yen5nc?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='344' yt:format='5'/><media:content url='rtsp://v8.cache8.c.youtube.com/CiILENy73wIaGQl35qcn9y6inBMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='344' yt:format='1'/><media:content url='rtsp://v8.cache8.c.youtube.com/CiILENy73wIaGQl35qcn9y6inBMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='344' yt:format='6'/><media:description type='plain'>Learn about a new "superpower" that isn't being taught in in 90% of US schools. 

Starring Bill Gates, Mark Zuckerberg, will.i.am, Chris Bosh, Jack Dorsey, Tony Hsieh, Drew Houston, Gabe Newell, Ruchi Sanghvi, Elena Silenok, Vanessa Hurst, and Hadi Partovi. Directed by Lesley Chilcott.

Code.org owes special thanks to all the cast and the film crew, and also Microsoft, Google/YouTube, Facebook, Amazon, and Twitter for helping us spread the word

(spanish translations by UruIT Team" http://uruit.com/ and Luisa Velarde. Portuguese by Rafael Sagula. If you want to help translate to other languages, visit http://bit.ly/codetranslate)</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=nKIu9yen5nc&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/nKIu9yen5nc/0.jpg' height='360' width='480' time='00:02:52'/><media:thumbnail url='http://i.ytimg.com/vi/nKIu9yen5nc/1.jpg' height='90' width='120' time='00:01:26'/><media:thumbnail url='http://i.ytimg.com/vi/nKIu9yen5nc/2.jpg' height='90' width='120' time='00:02:52'/><media:thumbnail url='http://i.ytimg.com/vi/nKIu9yen5nc/3.jpg' height='90' width='120' time='00:04:18'/><media:title type='plain'>What most schools don't teach</media:title><yt:duration seconds='344'/></media:group><gd:rating average='4.873588' max='5' min='1' numRaters='78347' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='8644048'/></entry>