<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/RzI9v_B4sxw</id><published>2013-02-23T05:12:22.000Z</published><updated>2013-02-27T07:26:07.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Entertainment' label='Entertainment'/><title type='text'>Game Of Thrones Season 3: Trailer</title><content type='text'>Game of Thrones Season 3 is coming. The new season returns on March 31st at 9pm. For more on Game of Thrones, go to http://itsh.bo/HpR8b1.
Song featured in this trailer is "Bones" by MS MR

Watch Game of Thrones online at HBO GO® http://itsh.bo/eIDxfw.

Watch Game of Thrones on one screen and connect on another: http://connect.hbo.com/game-thrones</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=RzI9v_B4sxw&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/RzI9v_B4sxw/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/RzI9v_B4sxw/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=RzI9v_B4sxw'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/RzI9v_B4sxw'/><author><name>GameofThrones</name><uri>http://gdata.youtube.com/feeds/api/users/GameofThrones</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/RzI9v_B4sxw/comments' countHint='18828'/></gd:comments><yt:hd/><media:group><media:category label='Entertainment' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Entertainment</media:category><media:content url='http://www.youtube.com/v/RzI9v_B4sxw?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='61' yt:format='5'/><media:content url='rtsp://v1.cache5.c.youtube.com/CiILENy73wIaGQkcs3jwvz0yRxMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='61' yt:format='1'/><media:content url='rtsp://v1.cache5.c.youtube.com/CiILENy73wIaGQkcs3jwvz0yRxMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='61' yt:format='6'/><media:description type='plain'>Game of Thrones Season 3 is coming. The new season returns on March 31st at 9pm. For more on Game of Thrones, go to http://itsh.bo/HpR8b1.
Song featured in this trailer is "Bones" by MS MR

Watch Game of Thrones online at HBO GO® http://itsh.bo/eIDxfw.

Watch Game of Thrones on one screen and connect on another: http://connect.hbo.com/game-thrones</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=RzI9v_B4sxw&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/RzI9v_B4sxw/0.jpg' height='360' width='480' time='00:00:30.500'/><media:thumbnail url='http://i.ytimg.com/vi/RzI9v_B4sxw/1.jpg' height='90' width='120' time='00:00:15.250'/><media:thumbnail url='http://i.ytimg.com/vi/RzI9v_B4sxw/2.jpg' height='90' width='120' time='00:00:30.500'/><media:thumbnail url='http://i.ytimg.com/vi/RzI9v_B4sxw/3.jpg' height='90' width='120' time='00:00:45.750'/><media:title type='plain'>Game Of Thrones Season 3: Trailer</media:title><yt:duration seconds='61'/></media:group><gd:rating average='4.8670735' max='5' min='1' numRaters='64908' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='14464937'/></entry>