<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/bc-fZaLbyJM</id><published>2012-12-15T06:04:29.000Z</published><updated>2013-02-08T07:42:41.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Film' label='Film &amp; Animation'/><title type='text'>Jurassic Park 3D  - Official Trailer (2013)</title><content type='text'>Jurassic Park  3D - Official Trailer (2013)


Genre : Science Fiction
Official Site : http://www.jurassicpark.com
Director:Steven Spielberg
Cast:Sam Neill, Laura Dern, Jeff Goldblum, Richard AttenboroughWriters:David Koepp, Michael Crichton

Synopsis
Universal Pictures will release Steven Spielberg's groundbreaking masterpiece JURASSIC PARK in 3D on April 5, 2013. With his remastering of the epic into a state-of-the-art 3D format, Spielberg introduces the three-time Academy Award®-winning blockbuster to a new generation of moviegoers and allows longtime fans to experience the world he envisioned in a way that was unimaginable during the film's original release. Starring Sam Neill, Laura Dern, Jeff Goldblum, Samuel L. Jackson and Richard Attenborough, the film based on the novel by Michael Crichton is produced by Kathleen Kennedy and Gerald R. Molen.</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=bc-fZaLbyJM&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/bc-fZaLbyJM/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/bc-fZaLbyJM/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=bc-fZaLbyJM'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/bc-fZaLbyJM'/><author><name>A2ZTrailers</name><uri>http://gdata.youtube.com/feeds/api/users/A2ZTrailers</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/bc-fZaLbyJM/comments' countHint='2'/></gd:comments><yt:hd/><media:group><media:category label='Film &amp; Animation' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Film</media:category><media:content url='http://www.youtube.com/v/bc-fZaLbyJM?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='135' yt:format='5'/><media:content url='rtsp://v8.cache8.c.youtube.com/CiILENy73wIaGQmTyNuiZZ_PbRMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='135' yt:format='1'/><media:content url='rtsp://v8.cache8.c.youtube.com/CiILENy73wIaGQmTyNuiZZ_PbRMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='135' yt:format='6'/><media:description type='plain'>Jurassic Park  3D - Official Trailer (2013)


Genre : Science Fiction
Official Site : http://www.jurassicpark.com
Director:Steven Spielberg
Cast:Sam Neill, Laura Dern, Jeff Goldblum, Richard AttenboroughWriters:David Koepp, Michael Crichton

Synopsis
Universal Pictures will release Steven Spielberg's groundbreaking masterpiece JURASSIC PARK in 3D on April 5, 2013. With his remastering of the epic into a state-of-the-art 3D format, Spielberg introduces the three-time Academy Award®-winning blockbuster to a new generation of moviegoers and allows longtime fans to experience the world he envisioned in a way that was unimaginable during the film's original release. Starring Sam Neill, Laura Dern, Jeff Goldblum, Samuel L. Jackson and Richard Attenborough, the film based on the novel by Michael Crichton is produced by Kathleen Kennedy and Gerald R. Molen.</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=bc-fZaLbyJM&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/bc-fZaLbyJM/0.jpg' height='360' width='480' time='00:01:07.500'/><media:thumbnail url='http://i.ytimg.com/vi/bc-fZaLbyJM/1.jpg' height='90' width='120' time='00:00:33.750'/><media:thumbnail url='http://i.ytimg.com/vi/bc-fZaLbyJM/2.jpg' height='90' width='120' time='00:01:07.500'/><media:thumbnail url='http://i.ytimg.com/vi/bc-fZaLbyJM/3.jpg' height='90' width='120' time='00:01:41.250'/><media:title type='plain'>Jurassic Park 3D  - Official Trailer (2013)</media:title><yt:duration seconds='135'/></media:group><gd:rating average='5.0' max='5' min='1' numRaters='6' rel='http://schemas.google.com/g/2005#overall'/><yt:recorded>2012-12-15</yt:recorded><yt:statistics favoriteCount='0' viewCount='6828'/></entry>