<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/iGng9NLo37Y</id><published>2012-10-19T16:35:06.000Z</published><updated>2013-02-25T13:34:15.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Film' label='Film &amp; Animation'/><title type='text'>Skyfall Official Trailer #2 (2012) - James Bond Movie HD</title><content type='text'>Subscribe to TRAILERS: http://bit.ly/sxaw6h
Subscribe to COMING SOON: http://bit.ly/H2vZUn
Skyfall Official Trailer #2 (2012) - James Bond Movie HD


Bond's loyalty to M is tested as her past comes back to haunt her. 


"skyfall trailer" "Daniel Craig" "Helen McCrory" "Javier Bardem" "John Logan" "Ian Fleming" "Ralph Fiennes" "Judi Dench" "Naomie Harris" "Albert Finney" "Ben Whishaw" "Berenice Marlohe" "james bond" 007 "behind the scenes" "video Blog" movieclips movie clips movieclipsDOTcom popuptrailer movieclipstrailer shanghai istanbul turkey "production design" "teaser for the trailer" "new skyfall trailer" "james bond new trailer" "skyfall international trailer" DCoscarelli</content><link rel='http://gdata.youtube.com/schemas/2007#video.in-response-to' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/qgk2q7rRPIM'/><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=iGng9NLo37Y&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/iGng9NLo37Y/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/iGng9NLo37Y/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=iGng9NLo37Y'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/iGng9NLo37Y'/><author><name>movieclipsTRAILERS</name><uri>http://gdata.youtube.com/feeds/api/users/movieclipsTRAILERS</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/iGng9NLo37Y/comments' countHint='300'/></gd:comments><yt:hd/><media:group><media:category label='Film &amp; Animation' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Film</media:category><media:content url='http://www.youtube.com/v/iGng9NLo37Y?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='123' yt:format='5'/><media:content url='rtsp://v1.cache8.c.youtube.com/CiILENy73wIaGQm23-jS9OBpiBMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='123' yt:format='1'/><media:content url='rtsp://v1.cache8.c.youtube.com/CiILENy73wIaGQm23-jS9OBpiBMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='123' yt:format='6'/><media:description type='plain'>Subscribe to TRAILERS: http://bit.ly/sxaw6h
Subscribe to COMING SOON: http://bit.ly/H2vZUn
Skyfall Official Trailer #2 (2012) - James Bond Movie HD


Bond's loyalty to M is tested as her past comes back to haunt her. 


"skyfall trailer" "Daniel Craig" "Helen McCrory" "Javier Bardem" "John Logan" "Ian Fleming" "Ralph Fiennes" "Judi Dench" "Naomie Harris" "Albert Finney" "Ben Whishaw" "Berenice Marlohe" "james bond" 007 "behind the scenes" "video Blog" movieclips movie clips movieclipsDOTcom popuptrailer movieclipstrailer shanghai istanbul turkey "production design" "teaser for the trailer" "new skyfall trailer" "james bond new trailer" "skyfall international trailer" DCoscarelli</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=iGng9NLo37Y&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/iGng9NLo37Y/0.jpg' height='360' width='480' time='00:01:01.500'/><media:thumbnail url='http://i.ytimg.com/vi/iGng9NLo37Y/1.jpg' height='90' width='120' time='00:00:30.750'/><media:thumbnail url='http://i.ytimg.com/vi/iGng9NLo37Y/2.jpg' height='90' width='120' time='00:01:01.500'/><media:thumbnail url='http://i.ytimg.com/vi/iGng9NLo37Y/3.jpg' height='90' width='120' time='00:01:32.250'/><media:title type='plain'>Skyfall Official Trailer #2 (2012) - James Bond Movie HD</media:title><yt:duration seconds='123'/></media:group><gd:rating average='4.7785716' max='5' min='1' numRaters='1120' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='419392'/></entry>