<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/qLZC67-NfOI</id><published>2012-11-27T14:48:25.000Z</published><updated>2013-03-05T08:08:23.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Entertainment' label='Entertainment'/><title type='text'>ABCD ( Any Body Can Dance ) - Official Trailer - Prabhudeva - Remo D`Souza</title><content type='text'>From India's biggest film studio, UTV Motion Pictures, and renowned choreographer &amp; director, Remo D'souza comes India's first dance film in 3D -- a spectacular entertainer that proves yet again that if you dare to dream, impossible is nothing!

In Cinemas: Feb 2013
Lead Cast: Prabhudeva, Salman Khan, Kay Kay Menon, Dharmesh Yelande, Lauren Gottlieb
Directed &amp; Choreographed By: Remo D'souza
Produced By: Ronnie Screwvala &amp; Siddharth Roy Kapur</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=qLZC67-NfOI&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/qLZC67-NfOI/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/qLZC67-NfOI/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=qLZC67-NfOI'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/qLZC67-NfOI'/><author><name>UTVMotionPictures</name><uri>http://gdata.youtube.com/feeds/api/users/UTVMotionPictures</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/qLZC67-NfOI/comments' countHint='2459'/></gd:comments><yt:hd/><media:group><media:category label='Entertainment' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Entertainment</media:category><media:content url='http://www.youtube.com/v/qLZC67-NfOI?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='153' yt:format='5'/><media:content url='rtsp://v3.cache3.c.youtube.com/CiILENy73wIaGQnifI2_60K2qBMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='153' yt:format='1'/><media:content url='rtsp://v3.cache3.c.youtube.com/CiILENy73wIaGQnifI2_60K2qBMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='153' yt:format='6'/><media:description type='plain'>From India's biggest film studio, UTV Motion Pictures, and renowned choreographer &amp; director, Remo D'souza comes India's first dance film in 3D -- a spectacular entertainer that proves yet again that if you dare to dream, impossible is nothing!

In Cinemas: Feb 2013
Lead Cast: Prabhudeva, Salman Khan, Kay Kay Menon, Dharmesh Yelande, Lauren Gottlieb
Directed &amp; Choreographed By: Remo D'souza
Produced By: Ronnie Screwvala &amp; Siddharth Roy Kapur</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=qLZC67-NfOI&amp;feature=youtube_gdata_player'/><media:restriction type='country' relationship='deny'>LY CU KP IR MM IQ</media:restriction><media:thumbnail url='http://i.ytimg.com/vi/qLZC67-NfOI/0.jpg' height='360' width='480' time='00:01:16.500'/><media:thumbnail url='http://i.ytimg.com/vi/qLZC67-NfOI/1.jpg' height='90' width='120' time='00:00:38.250'/><media:thumbnail url='http://i.ytimg.com/vi/qLZC67-NfOI/2.jpg' height='90' width='120' time='00:01:16.500'/><media:thumbnail url='http://i.ytimg.com/vi/qLZC67-NfOI/3.jpg' height='90' width='120' time='00:01:54.750'/><media:title type='plain'>ABCD ( Any Body Can Dance ) - Official Trailer - Prabhudeva - Remo D`Souza</media:title><yt:duration seconds='153'/></media:group><gd:rating average='4.7534637' max='5' min='1' numRaters='10465' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='3218932'/></entry>