<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/tXsyGFXjzcY</id><published>2011-11-14T08:45:05.000Z</published><updated>2013-02-01T15:14:38.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Entertainment' label='Entertainment'/><title type='text'>Titanic 3D - Trailer</title><content type='text'>Titanic is a 1997 American epic romance and disaster film directed, written, co-produced, and co-edited by James Cameron. A fictionalized account of the sinking of the RMS Titanic, it stars Leonardo DiCaprio as Jack Dawson, Kate Winslet as Rose DeWitt Bukater and Billy Zane as Rose's fiancé, Cal Hockley. Jack and Rose are members of different social classes who fall in love aboard the ship during its ill-fated maiden voyage. Revisit the movie in 3D this time.


For more Updates, 
visit http://www.youtube.com/foxstarindia

For More Titanic Updates, Like us on Facebook http://www.facebook.com/titanicmovieindia

"LIKE" our Facebook page https://www.facebook.com/FoxStarIndia</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=tXsyGFXjzcY&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/tXsyGFXjzcY/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/tXsyGFXjzcY/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=tXsyGFXjzcY'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/tXsyGFXjzcY'/><author><name>FoxStarIndia</name><uri>http://gdata.youtube.com/feeds/api/users/FoxStarIndia</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/tXsyGFXjzcY/comments' countHint='50'/></gd:comments><media:group><media:category label='Entertainment' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Entertainment</media:category><media:content url='http://www.youtube.com/v/tXsyGFXjzcY?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='127' yt:format='5'/><media:content url='rtsp://v6.cache8.c.youtube.com/CiILENy73wIaGQnGzeNVGDJ7tRMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='127' yt:format='1'/><media:content url='rtsp://v6.cache8.c.youtube.com/CiILENy73wIaGQnGzeNVGDJ7tRMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='127' yt:format='6'/><media:description type='plain'>Titanic is a 1997 American epic romance and disaster film directed, written, co-produced, and co-edited by James Cameron. A fictionalized account of the sinking of the RMS Titanic, it stars Leonardo DiCaprio as Jack Dawson, Kate Winslet as Rose DeWitt Bukater and Billy Zane as Rose's fiancé, Cal Hockley. Jack and Rose are members of different social classes who fall in love aboard the ship during its ill-fated maiden voyage. Revisit the movie in 3D this time.


For more Updates, 
visit http://www.youtube.com/foxstarindia

For More Titanic Updates, Like us on Facebook http://www.facebook.com/titanicmovieindia

"LIKE" our Facebook page https://www.facebook.com/FoxStarIndia</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=tXsyGFXjzcY&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/tXsyGFXjzcY/0.jpg' height='360' width='480' time='00:01:03.500'/><media:thumbnail url='http://i.ytimg.com/vi/tXsyGFXjzcY/1.jpg' height='90' width='120' time='00:00:31.750'/><media:thumbnail url='http://i.ytimg.com/vi/tXsyGFXjzcY/2.jpg' height='90' width='120' time='00:01:03.500'/><media:thumbnail url='http://i.ytimg.com/vi/tXsyGFXjzcY/3.jpg' height='90' width='120' time='00:01:35.250'/><media:title type='plain'>Titanic 3D - Trailer</media:title><yt:duration seconds='127'/></media:group><gd:rating average='4.950719' max='5' min='1' numRaters='487' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='151765'/></entry>