<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:gml='http://www.opengis.net/gml' xmlns:yt='http://gdata.youtube.com/schemas/2007' xmlns:georss='http://www.georss.org/georss'><id>http://gdata.youtube.com/feeds/api/videos/vGpjlfCfe2Y</id><published>2012-12-09T14:46:46.000Z</published><updated>2013-03-04T08:17:55.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Film' label='Film &amp; Animation'/><title type='text'>Oblivion Trailer (2013)</title><content type='text'>Earth is a memory worth fighting for...  Watch new Trailer here : http://www.youtube.com/watch?v=FH7MM3c8mJI The first Oblivion Trailer starring Tom Cruise. An original and groundbreaking cinematic event from the director of TRON: Legacy and the producer of Rise of the Planet of the Apes. On a spectacular future Earth that has evolved beyond recognition, one man's confrontation with the past will lead him on a journey of redemption and discovery as he battles to save mankind. ack Harper (Cruise) is one of the last few drone repairmen stationed on Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack's mission is nearly complete.

Living in and patrolling the breathtaking skies from thousands of feet above, his soaring existence is brought crashing down when he rescues a beautiful stranger from a downed spacecraft. Her arrival triggers a chain of events that forces him to question everything he knows and puts the fate of humanity in his hands.

Oblivion was shot in stunning digital 4K resolution on location across the United States and Iceland.

Oblivion Official Trailer. Join us on Facebook http://facebook.com/FreshMovieTrailers &amp; http://twitter.com/mytrailerisrich and subscribe now to get the best and the latest movie trailers, clips and videos !</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=vGpjlfCfe2Y&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/vGpjlfCfe2Y/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/vGpjlfCfe2Y/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=vGpjlfCfe2Y'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/vGpjlfCfe2Y'/><author><name>FilmsActuTrailers</name><uri>http://gdata.youtube.com/feeds/api/users/FilmsActuTrailers</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/vGpjlfCfe2Y/comments' countHint='1201'/></gd:comments><georss:where><gml:Point><gml:pos>40.7475204468 -73.9951019287</gml:pos></gml:Point></georss:where><yt:hd/><media:group><media:category label='Film &amp; Animation' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Film</media:category><media:content url='http://www.youtube.com/v/vGpjlfCfe2Y?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='155' yt:format='5'/><media:content url='rtsp://r8---sn-a5m7zu7s.c.youtube.com/CiILENy73wIaGQlme5_wlWNqvBMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='155' yt:format='1'/><media:content url='rtsp://r8---sn-a5m7zu7s.c.youtube.com/CiILENy73wIaGQlme5_wlWNqvBMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='155' yt:format='6'/><media:description type='plain'>Earth is a memory worth fighting for...  Watch new Trailer here : http://www.youtube.com/watch?v=FH7MM3c8mJI The first Oblivion Trailer starring Tom Cruise. An original and groundbreaking cinematic event from the director of TRON: Legacy and the producer of Rise of the Planet of the Apes. On a spectacular future Earth that has evolved beyond recognition, one man's confrontation with the past will lead him on a journey of redemption and discovery as he battles to save mankind. ack Harper (Cruise) is one of the last few drone repairmen stationed on Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack's mission is nearly complete.

Living in and patrolling the breathtaking skies from thousands of feet above, his soaring existence is brought crashing down when he rescues a beautiful stranger from a downed spacecraft. Her arrival triggers a chain of events that forces him to question everything he knows and puts the fate of humanity in his hands.

Oblivion was shot in stunning digital 4K resolution on location across the United States and Iceland.

Oblivion Official Trailer. Join us on Facebook http://facebook.com/FreshMovieTrailers &amp; http://twitter.com/mytrailerisrich and subscribe now to get the best and the latest movie trailers, clips and videos !</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=vGpjlfCfe2Y&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/vGpjlfCfe2Y/0.jpg' height='360' width='480' time='00:01:17.500'/><media:thumbnail url='http://i.ytimg.com/vi/vGpjlfCfe2Y/1.jpg' height='90' width='120' time='00:00:38.750'/><media:thumbnail url='http://i.ytimg.com/vi/vGpjlfCfe2Y/2.jpg' height='90' width='120' time='00:01:17.500'/><media:thumbnail url='http://i.ytimg.com/vi/vGpjlfCfe2Y/3.jpg' height='90' width='120' time='00:01:56.250'/><media:title type='plain'>Oblivion Trailer (2013)</media:title><yt:duration seconds='155'/></media:group><gd:rating average='4.84845' max='5' min='1' numRaters='4355' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='1868890'/></entry>