<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/XFnGhrC_3Gs</id><published>2010-01-19T17:46:16.000Z</published><updated>2013-03-04T05:42:58.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Tech' label='Science &amp; Technology'/><title type='text'>David Blaine: How I held my breath for 17 min</title><content type='text'>http://www.ted.com In this highly personal talk from TEDMED, magician and stuntman David Blaine describes what it took to hold his breath underwater for 17 minutes -- a world record (only two minutes shorter than this entire talk!) -- and what his often death-defying work means to him. Warning: do NOT try this at home.

TEDTalks is a daily video podcast of the best talks and performances from the TED Conference, where the world's leading thinkers and doers give the talk of their lives in 18 minutes. TED stands for Technology, Entertainment, Design, and TEDTalks cover these topics as well as science, business, development and the arts. Closed captions and translated subtitles in a variety of languages are now available on TED.com, at http://www.ted.com/translate.

Follow us on Twitter
http://www.twitter.com/tednews
 
Checkout our Facebook page for TED exclusives
https://www.facebook.com/TED</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=XFnGhrC_3Gs&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/XFnGhrC_3Gs/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/XFnGhrC_3Gs/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=XFnGhrC_3Gs'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/XFnGhrC_3Gs'/><author><name>TEDtalksDirector</name><uri>http://gdata.youtube.com/feeds/api/users/TEDtalksDirector</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/XFnGhrC_3Gs/comments' countHint='6382'/></gd:comments><media:group><media:category label='Science &amp; Technology' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Tech</media:category><media:content url='http://www.youtube.com/v/XFnGhrC_3Gs?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='1219' yt:format='5'/><media:content url='rtsp://v8.cache3.c.youtube.com/CiILENy73wIaGQlr3L-whsZZXBMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='1219' yt:format='1'/><media:content url='rtsp://v8.cache3.c.youtube.com/CiILENy73wIaGQlr3L-whsZZXBMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='1219' yt:format='6'/><media:description type='plain'>http://www.ted.com In this highly personal talk from TEDMED, magician and stuntman David Blaine describes what it took to hold his breath underwater for 17 minutes -- a world record (only two minutes shorter than this entire talk!) -- and what his often death-defying work means to him. Warning: do NOT try this at home.

TEDTalks is a daily video podcast of the best talks and performances from the TED Conference, where the world's leading thinkers and doers give the talk of their lives in 18 minutes. TED stands for Technology, Entertainment, Design, and TEDTalks cover these topics as well as science, business, development and the arts. Closed captions and translated subtitles in a variety of languages are now available on TED.com, at http://www.ted.com/translate.

Follow us on Twitter
http://www.twitter.com/tednews
 
Checkout our Facebook page for TED exclusives
https://www.facebook.com/TED</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=XFnGhrC_3Gs&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/XFnGhrC_3Gs/0.jpg' height='360' width='480' time='00:10:09.500'/><media:thumbnail url='http://i.ytimg.com/vi/XFnGhrC_3Gs/1.jpg' height='90' width='120' time='00:05:04.750'/><media:thumbnail url='http://i.ytimg.com/vi/XFnGhrC_3Gs/2.jpg' height='90' width='120' time='00:10:09.500'/><media:thumbnail url='http://i.ytimg.com/vi/XFnGhrC_3Gs/3.jpg' height='90' width='120' time='00:15:14.250'/><media:title type='plain'>David Blaine: How I held my breath for 17 min</media:title><yt:duration seconds='1219'/></media:group><gd:rating average='4.8668284' max='5' min='1' numRaters='16460' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='2167626'/></entry>