<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom' xmlns:media='http://search.yahoo.com/mrss/' xmlns:gd='http://schemas.google.com/g/2005' xmlns:yt='http://gdata.youtube.com/schemas/2007'><id>http://gdata.youtube.com/feeds/api/videos/wZ4QNS__zDM</id><published>2013-02-14T07:24:58.000Z</published><updated>2013-02-20T06:36:04.000Z</updated><category scheme='http://schemas.google.com/g/2005#kind' term='http://gdata.youtube.com/schemas/2007#video'/><category scheme='http://gdata.youtube.com/schemas/2007/categories.cat' term='Entertainment' label='Entertainment'/><title type='text'>Dude &amp; Darlings Part 1 -- Prabhas,Anushka &amp; Richa</title><content type='text'>Mirchi Special Interview of Prabhas,Anushka &amp; Richa

For Latest Film Content Subscribe to : http://www.youtube.com/maatv
For Songs and Music Subscribe to: http://www.youtube.com/maamusic
For Traditional and Trendy Cookery Stuff Subscribe to: http://www.youtube.com/maacookery
For Movie Related Subscribe to: http://www.youtube.com/maamoviez
For Comedy Subscribe to : http://www.youtube.com/maacomedy
For gameshows Subscribe to : http://www.youtube.com/maagameshows
For Supersinger &amp; Rangam Subscribe to: http://www.youtube.com/maareality
LIKE us on FACEBOOK : http://www.facebook.com/maatv
Follow Us on TWITTER http://www.twitter.com/maanetwork</content><link rel='alternate' type='text/html' href='http://www.youtube.com/watch?v=wZ4QNS__zDM&amp;feature=youtube_gdata'/><link rel='http://gdata.youtube.com/schemas/2007#video.responses' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/wZ4QNS__zDM/responses'/><link rel='http://gdata.youtube.com/schemas/2007#video.related' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/wZ4QNS__zDM/related'/><link rel='http://gdata.youtube.com/schemas/2007#mobile' type='text/html' href='http://m.youtube.com/details?v=wZ4QNS__zDM'/><link rel='self' type='application/atom+xml' href='http://gdata.youtube.com/feeds/api/videos/wZ4QNS__zDM'/><author><name>maatv</name><uri>http://gdata.youtube.com/feeds/api/users/maatv</uri></author><gd:comments><gd:feedLink rel='http://gdata.youtube.com/schemas/2007#comments' href='http://gdata.youtube.com/feeds/api/videos/wZ4QNS__zDM/comments' countHint='3'/></gd:comments><media:group><media:category label='Entertainment' scheme='http://gdata.youtube.com/schemas/2007/categories.cat'>Entertainment</media:category><media:content url='http://www.youtube.com/v/wZ4QNS__zDM?version=3&amp;f=videos&amp;app=youtube_gdata' type='application/x-shockwave-flash' medium='video' isDefault='true' expression='full' duration='591' yt:format='5'/><media:content url='rtsp://v8.cache4.c.youtube.com/CiILENy73wIaGQkzzP8vNRCewRMYDSANFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='591' yt:format='1'/><media:content url='rtsp://v8.cache4.c.youtube.com/CiILENy73wIaGQkzzP8vNRCewRMYESARFEgGUgZ2aWRlb3MM/0/0/0/video.3gp' type='video/3gpp' medium='video' expression='full' duration='591' yt:format='6'/><media:description type='plain'>Mirchi Special Interview of Prabhas,Anushka &amp; Richa

For Latest Film Content Subscribe to : http://www.youtube.com/maatv
For Songs and Music Subscribe to: http://www.youtube.com/maamusic
For Traditional and Trendy Cookery Stuff Subscribe to: http://www.youtube.com/maacookery
For Movie Related Subscribe to: http://www.youtube.com/maamoviez
For Comedy Subscribe to : http://www.youtube.com/maacomedy
For gameshows Subscribe to : http://www.youtube.com/maagameshows
For Supersinger &amp; Rangam Subscribe to: http://www.youtube.com/maareality
LIKE us on FACEBOOK : http://www.facebook.com/maatv
Follow Us on TWITTER http://www.twitter.com/maanetwork</media:description><media:keywords/><media:player url='http://www.youtube.com/watch?v=wZ4QNS__zDM&amp;feature=youtube_gdata_player'/><media:thumbnail url='http://i.ytimg.com/vi/wZ4QNS__zDM/0.jpg' height='360' width='480' time='00:04:55.500'/><media:thumbnail url='http://i.ytimg.com/vi/wZ4QNS__zDM/1.jpg' height='90' width='120' time='00:02:27.750'/><media:thumbnail url='http://i.ytimg.com/vi/wZ4QNS__zDM/2.jpg' height='90' width='120' time='00:04:55.500'/><media:thumbnail url='http://i.ytimg.com/vi/wZ4QNS__zDM/3.jpg' height='90' width='120' time='00:07:23.250'/><media:title type='plain'>Dude &amp; Darlings Part 1 -- Prabhas,Anushka &amp; Richa</media:title><yt:duration seconds='591'/></media:group><gd:rating average='4.6862745' max='5' min='1' numRaters='51' rel='http://schemas.google.com/g/2005#overall'/><yt:statistics favoriteCount='0' viewCount='38729'/></entry>